### ISSUE TITLE
support for _FILE extension of env variables

### ISSUE THREAD

**Issue by cblomart** [mssola/cconfig#8]
In  some docker swarm samples for [secrets](https://docs.docker.com/engine/swarm/secrets/) (see Use Secrets in Compose) we see things like:

```yaml
[...]
services:
   db:
     image: mysql:latest
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password
[...]
```

Does cconfig supports the "_FILE" extension that tells that the environment variable value is to be taken from the content of a file?

This would be usefull to fully leverage the power of docker secrets!

(i would look into it but i don't speak ruby fluently)
